# Generated by Django 3.2.18 on 2023-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentlocationmodel',
            old_name='loc_cords',
            new_name='loc_city',
        ),
        migrations.RenameField(
            model_name='currentlocationmodel',
            old_name='loc_text',
            new_name='loc_cords_lat',
        ),
        migrations.AddField(
            model_name='currentlocationmodel',
            name='loc_cords_long',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='currentlocationmodel',
            name='loc_country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='currentlocationmodel',
            name='loc_postalCode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='currentlocationmodel',
            name='loc_region',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='currentlocationmodel',
            name='loc_street',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
