# Generated by Django 3.2.18 on 2023-05-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_location', '0002_auto_20230513_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlocationmodel',
            name='driver',
            field=models.BooleanField(default=False),
        ),
    ]
