# Generated by Django 3.2.18 on 2023-08-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_location', '0003_currentlocationmodel_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_cords_lat', models.CharField(blank=True, max_length=300, null=True)),
                ('user_cords_long', models.CharField(blank=True, max_length=300, null=True)),
                ('loc_cords_lat', models.CharField(blank=True, max_length=300, null=True)),
                ('loc_cords_long', models.CharField(blank=True, max_length=300, null=True)),
                ('user_location', models.CharField(blank=True, max_length=300, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=300, null=True)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='requested', max_length=50)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_driver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
