# Generated by Django 3.2.18 on 2023-08-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_location', '0006_transactionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'ordering': ['-payment_date']},
        ),
    ]
