# Generated by Django 3.2.18 on 2023-08-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0005_drivermodel'),
        ('App_location', '0007_alter_transactionmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemodel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_driver', to='App_auth.drivermodel'),
        ),
    ]
