# Generated by Django 3.2.18 on 2023-08-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_location', '0008_alter_ridemodel_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemodel',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('on ride', 'On Ride'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='Requested', max_length=50),
        ),
    ]
