# Generated by Django 3.2.18 on 2023-08-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_location', '0009_alter_ridemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemodel',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('On Ride', 'On Ride'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Requested', max_length=50),
        ),
    ]
