# Generated by Django 3.2.18 on 2023-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_location', '0010_alter_ridemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemodel',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('On Ride', 'On Ride'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Payment Done', 'Payment Done')], default='Requested', max_length=50),
        ),
    ]
